### ISSUE TITLE
[30m] Choose an URL for the results page on the website

### ISSUE THREAD

**Issue by RemiBardon** [chocoteam/PerformanceAction#1]
We'd like a private URL, not indexed by robots and not referenced on the website.

**Comment by cprudhom** [comment]
what about `https://choco-solver.org/docs/benchmarks/` ? 
That supposes you create and write in `Benchmarks.md` file, in `/docs/` dir.
Do you need me to create it?

**Comment by RemiBardon** [comment]
I searched around, and found interesting things:

- [Hugo does not provide a turnkey solution for removing a page from `sitemap.xml`](https://github.com/gohugoio/hugo/issues/653). To do this, you need to create a [custom template for `sitemap.xml`](https://github.com/dereckcurry/hugo-sitemap-exclude). It would be quite unfortunate to create a custom sitemap template just for 2/3 pages… but it's doable.
- The [`headless: true` Front Matter Variable](https://gohugo.io/content-management/page-bundles/#headless-bundle) allows one to disable the publishing of a bundle
  
  > A headless bundle is a bundle that is configured to not get published anywhere:
  > 
  > - It will have no `Permalink` and no rendered HTML in `public/`.
  > - It will not be part of `.Site.RegularPages`, etc.
  
  Unfortunately, there is no way to access the page after, even after setting the `url` Front Matter variable.

@cprudhom Is it a problem if the page is visible/indexed?

**Comment by cprudhom** [comment]
I don't really care for now. I don't want you to spend too much time on this specific topic.
Just keep in mind that the target URL should be easy to change.

**Comment by RemiBardon** [comment]
> what about `https://choco-solver.org/docs/benchmarks/` ?

I had thought about `/docs/test-results`, but `/docs/benchmarks/` is good too.

> That supposes you create and write in `Benchmarks.md` file, in `/docs/` dir.
> Do you need me to create it?

I know a bit about Hugo – I've created [a website for my personal project](https://monkiprojects.com) and [a travel blog](https://heloise-travel.cleverapps.io), both with custom theme and multilingual, hosted on [Clever Cloud](https://www.clever-cloud.com/en/) – so I can do it myself 😉

**Comment by RemiBardon** [comment]
> Just keep in mind that the target URL should be easy to change.

Yeah, I will make sure it is.

**Comment by cprudhom** [comment]
Maybe we can simply start by adding a `draft` tag?

**Comment by RemiBardon** [comment]
Yes, but it won't be published online at all 💁🏻‍♂️

**Comment by cprudhom** [comment]
You are right, that's a strong limitation

**Comment by RemiBardon** [comment]
I keep it as draft for now. Can you create a branch on [website](https://github.com/chocoteam/website) for us to "send" generated pages? We will check the correct creation locally with `-D`. You will be able to merge it when it's working correctly.

**Comment by RemiBardon** [comment]
@cprudhom Are we good with:

- `/docs/benchmarks/optimization[.html]` for optimization ('s' or 'z', you decide)
- `/docs/benchmarks/satisfaction[.html]` for satisfaction

?

**Comment by cprudhom** [comment]
The [branch](https://github.com/chocoteam/website/tree/topic-benchmarks) is now created.

**Comment by cprudhom** [comment]
> * `/docs/benchmarks/optimization[.html]` for optimization
> * `/docs/benchmarks/satisfaction[.html]` for satisfaction

I'm good with that.
