### ISSUE TITLE
[2H] Parse JSON output data

### ISSUE THREAD

**Issue by FlorianDussable** [chocoteam/PerformanceAction#6]
Need to parse current and previous results to compare

**Comment by RemiBardon** [comment]
## Analyse formatting of files

Files are a mix of space separated CSV and JSON

### Space separated CSV structure

- Column 1 is input file (unique)
- Column 2 is time taken to prove the solution (`-1` if never proven)
- Column 3 is output data in JSON

Lines order is deterministic.

### Output JSON structure

Results are a stored in an array. Each result is a JSON object.

I case of optimisation testing, this object looks like `{"bound":23,"time":12}`, but we should not make any assumption about this structure, as it might change in the future (more fields).

All objects have (but it's better not to make assumptions):

1. String keys and numeric values
2. A `"time"` key

Results are ordered in the array.
